version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Python backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns:
          - "*"

  # Maintain dependencies for npm frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"
