import { defineConfig, devices } from '@playwright/test';
import path from 'path';

export const STORAGE_STATE = path.join(__dirname, 'playwright/.auth/user.json');

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false, // Run sequentially to avoid state collisions
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    contextOptions: {
      // Inject global flag so the app knows it's being driven by Playwright
      // We use this to bypass Captcha
    },
    actionTimeout: 10000,
  },
  projects: [
    // Setup project
    {
      name: 'setup',
      testMatch: /auth\.setup\.ts/,
    },
    // Desktop Viewport
    {
      name: 'chromium-desktop',
      use: {
        ...devices['Desktop Chrome'],
        // Use storage state generated by setup project
        storageState: STORAGE_STATE,
      },
      dependencies: ['setup'],
    },
    // Mobile Viewport
    {
      name: 'chromium-mobile',
      use: {
        ...devices['Pixel 5'],
        // Use storage state generated by setup project
        storageState: STORAGE_STATE,
      },
      dependencies: ['setup'],
    },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
    timeout: 120000,
  },
});
