import { defineConfig, devices } from '@playwright/test';
import path from 'path';

export const STORAGE_STATE = path.join(__dirname, 'playwright/.auth/user.json');

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false, // Run sequentially to avoid state collisions
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    // Setup project
    {
      name: 'setup',
      testMatch: /auth\.setup\.ts/,
    },
    // Desktop Viewport
    {
      name: 'chromium-desktop',
      use: {
        ...devices['Desktop Chrome'],
        // Use storage state generated by setup project
        storageState: STORAGE_STATE,
      },
      dependencies: ['setup'],
    },
    // Mobile Viewport
    {
      name: 'chromium-mobile',
      use: {
        ...devices['Pixel 5'],
        // Use storage state generated by setup project
        storageState: STORAGE_STATE,
      },
      dependencies: ['setup'],
    },
  ],
  webServer: {
    command: 'npm run start', // We can run after npm run build for clean tests
    url: 'http://localhost:3000',
    reuseExistingServer: true,
    timeout: 120000,
  },
});
