"""add user model

Revision ID: 751be1fd11a4
Revises: 9bbb2aa58d0e
Create Date: 2026-07-14 17:35:21.818658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751be1fd11a4'
down_revision: Union[str, Sequence[str], None] = '9bbb2aa58d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Seed default admin user
    import uuid
    # Hash for 'admin123' using argon2
    default_hash = "$argon2id$v=19$m=65536,t=3,p=4$q+n9D5y2O0f8e9F+w7v3$u1O/3b5P2j2v5N/Y5k+Q6Q"
    op.bulk_insert(
        users_table,
        [
            {
                "id": uuid.uuid4(),
                "username": "admin",
                "email": "admin@example.com",
                "hashed_password": default_hash,
                "is_active": True,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
