"""initial_schema

Revision ID: 9bbb2aa58d0e
Revises: 2802f86835b1
Create Date: 2026-07-13 13:11:09.337542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bbb2aa58d0e'
down_revision: Union[str, Sequence[str], None] = '2802f86835b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='run_status', create_constraint=True), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_step >= 0', name='ck_agent_run_step_non_negative'),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name='ck_agent_run_finished_after_started'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_created_at', 'agent_runs', ['created_at'], unique=False)
    op.create_index('ix_agent_run_session_id', 'agent_runs', ['session_id'], unique=False)
    op.create_index('ix_agent_run_status', 'agent_runs', ['status'], unique=False)
    op.create_index('ix_agent_run_status_created_at', 'agent_runs', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AGENT', 'USER', name='actor_type', create_constraint=True), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='audit_severity', create_constraint=True), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILURE', 'PARTIAL', 'UNKNOWN', name='audit_outcome', create_constraint=True), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action <> ''", name='ck_audit_log_action_not_empty'),
    sa.CheckConstraint("actor_id <> ''", name='ck_audit_log_actor_id_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_log_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('ix_audit_log_actor_created_at', 'audit_logs', ['actor_type', 'actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_log_outcome', 'audit_logs', ['outcome'], unique=False)
    op.create_index('ix_audit_log_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_log_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_log_severity', 'audit_logs', ['severity'], unique=False)
    op.create_index('ix_audit_log_severity_outcome_created_at', 'audit_logs', ['severity', 'outcome', 'created_at'], unique=False)
    op.create_index('ix_audit_log_trace_id', 'audit_logs', ['trace_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('WEB', 'PDF', 'GITHUB', 'LOCAL', 'MARKDOWN', 'API', 'VIDEO', 'DOCS', name='document_source_type', create_constraint=True), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('repository_url', sa.String(length=2048), nullable=True),
    sa.Column('repository_branch', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('encoding', sa.String(length=50), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'READY', 'FAILED', 'ARCHIVED', name='document_status', create_constraint=True), nullable=False),
    sa.Column('crawl_status', sa.Enum('PENDING', 'CRAWLING', 'SUCCESS', 'FAILED', name='document_crawl_status', create_constraint=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_count', sa.Integer(), nullable=False),
    sa.Column('graph_node_count', sa.Integer(), nullable=False),
    sa.Column('vector_collection', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('graph_namespace', sa.String(length=255), nullable=True),
    sa.Column('graph_version', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_count >= 0', name='ck_knowledgedocument_chunk_count_non_negative'),
    sa.CheckConstraint('embedding_count >= 0', name='ck_knowledgedocument_embedding_count_non_negative'),
    sa.CheckConstraint('graph_node_count >= 0', name='ck_knowledgedocument_graph_node_count_non_negative'),
    sa.CheckConstraint('trust_score >= 0.000 AND trust_score <= 1.000', name='ck_knowledgedocument_trust_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledgedocument_checksum', 'knowledge_documents', ['checksum_sha256'], unique=False)
    op.create_index('ix_knowledgedocument_content_hash', 'knowledge_documents', ['content_hash'], unique=False)
    op.create_index('ix_knowledgedocument_graph_namespace', 'knowledge_documents', ['graph_namespace'], unique=False)
    op.create_index('ix_knowledgedocument_graph_status', 'knowledge_documents', ['graph_namespace', 'status'], unique=False)
    op.create_index('ix_knowledgedocument_lang_trust', 'knowledge_documents', ['language', 'trust_score'], unique=False)
    op.create_index('ix_knowledgedocument_language', 'knowledge_documents', ['language'], unique=False)
    op.create_index('ix_knowledgedocument_last_synced_at', 'knowledge_documents', ['last_synced_at'], unique=False)
    op.create_index('ix_knowledgedocument_source_status', 'knowledge_documents', ['source_type', 'status'], unique=False)
    op.create_index('ix_knowledgedocument_source_type', 'knowledge_documents', ['source_type'], unique=False)
    op.create_index('ix_knowledgedocument_status', 'knowledge_documents', ['status'], unique=False)
    op.create_index('ix_knowledgedocument_trust_score', 'knowledge_documents', ['trust_score'], unique=False)
    op.create_index('ix_knowledgedocument_vector_collection', 'knowledge_documents', ['vector_collection'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.Enum('EPISODIC', 'SEMANTIC', 'PROCEDURAL', 'WORKING', name='memory_type', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('embedding_id', sa.Uuid(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('access_count >= 0', name='ck_memory_entry_access_count_non_negative'),
    sa.CheckConstraint('embedding_model IS NULL OR embedding_id IS NOT NULL', name='ck_memory_entry_embedding_model_with_id'),
    sa.CheckConstraint('importance_score >= 0.000 AND importance_score <= 1.000', name='ck_memory_entry_importance_score_range'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_entry_agent_run_id', 'memory_entries', ['agent_run_id'], unique=False)
    op.create_index('ix_memory_entry_embedding_id', 'memory_entries', ['embedding_id'], unique=False)
    op.create_index('ix_memory_entry_memory_type', 'memory_entries', ['memory_type'], unique=False)
    op.create_index('ix_memory_entry_namespace', 'memory_entries', ['namespace'], unique=False)
    op.create_index('ix_memory_entry_namespace_type', 'memory_entries', ['namespace', 'memory_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='task_status', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='task_priority', create_constraint=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name='ck_task_finished_after_started'),
    sa.CheckConstraint('max_retries >= 0', name='ck_task_max_retries_non_negative'),
    sa.CheckConstraint('position >= 0', name='ck_task_position_non_negative'),
    sa.CheckConstraint('retry_count <= max_retries', name='ck_task_retry_count_lte_max'),
    sa.CheckConstraint('retry_count >= 0', name='ck_task_retry_count_non_negative'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'position', name='uq_task_agent_run_position')
    )
    op.create_index('ix_task_agent_run_id', 'tasks', ['agent_run_id'], unique=False)
    op.create_index('ix_task_agent_run_position', 'tasks', ['agent_run_id', 'position'], unique=False)
    op.create_index('ix_task_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_task_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_task_status_priority', 'tasks', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_status_priority', table_name='tasks')
    op.drop_index('ix_task_status', table_name='tasks')
    op.drop_index('ix_task_priority', table_name='tasks')
    op.drop_index('ix_task_agent_run_position', table_name='tasks')
    op.drop_index('ix_task_agent_run_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_memory_entry_namespace_type', table_name='memory_entries')
    op.drop_index('ix_memory_entry_namespace', table_name='memory_entries')
    op.drop_index('ix_memory_entry_memory_type', table_name='memory_entries')
    op.drop_index('ix_memory_entry_embedding_id', table_name='memory_entries')
    op.drop_index('ix_memory_entry_agent_run_id', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index('ix_knowledgedocument_vector_collection', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_trust_score', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_status', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_source_type', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_source_status', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_last_synced_at', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_language', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_lang_trust', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_graph_status', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_graph_namespace', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_content_hash', table_name='knowledge_documents')
    op.drop_index('ix_knowledgedocument_checksum', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_audit_log_trace_id', table_name='audit_logs')
    op.drop_index('ix_audit_log_severity_outcome_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_log_severity', table_name='audit_logs')
    op.drop_index('ix_audit_log_resource', table_name='audit_logs')
    op.drop_index('ix_audit_log_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_log_outcome', table_name='audit_logs')
    op.drop_index('ix_audit_log_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_log_correlation_id', table_name='audit_logs')
    op.drop_index('ix_audit_log_actor_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_log_actor', table_name='audit_logs')
    op.drop_index('ix_audit_log_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agent_run_status_created_at', table_name='agent_runs')
    op.drop_index('ix_agent_run_status', table_name='agent_runs')
    op.drop_index('ix_agent_run_session_id', table_name='agent_runs')
    op.drop_index('ix_agent_run_created_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS run_status CASCADE")
    op.execute("DROP TYPE IF EXISTS task_status CASCADE")
    op.execute("DROP TYPE IF EXISTS task_priority CASCADE")
    op.execute("DROP TYPE IF EXISTS memory_type CASCADE")
    op.execute("DROP TYPE IF EXISTS document_source_type CASCADE")
    op.execute("DROP TYPE IF EXISTS document_status CASCADE")
    op.execute("DROP TYPE IF EXISTS document_crawl_status CASCADE")
    op.execute("DROP TYPE IF EXISTS log_actor_type CASCADE")
    op.execute("DROP TYPE IF EXISTS log_severity CASCADE")
    op.execute("DROP TYPE IF EXISTS log_outcome CASCADE")
    # ### end Alembic commands ###
