"""Add documents and document_chunks tables

Revision ID: bb651056f352
Revises: 37c46316c0a8
Create Date: 2026-09-19 18:40:40.165440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb651056f352'
down_revision: Union[str, Sequence[str], None] = '37c46316c0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('command', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('env_vars', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tools_cache', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_servers_project_id'), 'mcp_servers', ['project_id'], unique=False)
    op.alter_column('agent_runs', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'current_plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'individual'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.alter_column('agent_runs', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_mcp_servers_project_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
