"""add role to user

Revision ID: daab246a259f
Revises: 751be1fd11a4
Create Date: 2026-07-14 17:51:05.001702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daab246a259f'
down_revision: Union[str, Sequence[str], None] = '751be1fd11a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='viewer', nullable=False))
    # Note: we update existing admin to admin role
    op.execute("UPDATE users SET role = 'admin' WHERE username = 'admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
