"""add_org_id_and_expires_at_to_memory

Revision ID: eea51b074ec7
Revises: bb651056f352
Create Date: 2026-09-20 21:49:41.947363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea51b074ec7'
down_revision: Union[str, Sequence[str], None] = 'bb651056f352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_entries', sa.Column('org_id', sa.Uuid(), nullable=False))
    op.add_column('memory_entries', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_memory_entries_expires_at'), 'memory_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memory_entries_org_id'), 'memory_entries', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_entries_org_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_expires_at'), table_name='memory_entries')
    op.drop_column('memory_entries', 'expires_at')
    op.drop_column('memory_entries', 'org_id')
    # ### end Alembic commands ###
